# Generated by Django 4.2.2 on 2024-01-28 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0002_user_remove_pdf_tags_pdf_cover_image_pdf_date_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='Publication_user',
        ),
    ]
