# Generated by Django 4.2.2 on 2024-02-06 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0004_pdf_publication_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Store_Name', models.CharField(max_length=1000)),
                ('Store_Address', models.CharField(max_length=1000)),
                ('banner', models.FileField(upload_to='advertisement_banner/')),
                ('location', models.CharField(max_length=250)),
                ('date', models.DateField()),
            ],
        ),
    ]
