# Generated by Django 4.2.2 on 2024-03-08 11:18

from django.db import migrations, models
import pdf.models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0005_advertisement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='banner',
            field=models.FileField(null=True, storage=pdf.models.PDFStorage(), upload_to='advertisement_banner/'),
        ),
        migrations.AlterField(
            model_name='pdf',
            name='cover_image',
            field=models.FileField(null=True, storage=pdf.models.PDFStorage(), upload_to='cover image/'),
        ),
        migrations.AlterField(
            model_name='pdf',
            name='file',
            field=models.FileField(storage=pdf.models.PDFStorage(), upload_to='pdfs/'),
        ),
        migrations.AlterField(
            model_name='publication_user',
            name='profile',
            field=models.FileField(null=True, storage=pdf.models.PDFStorage(), upload_to='profile/'),
        ),
    ]
